name: Build and Deploy Flutter Web
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build Web
    runs-on: macos-latest
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=${{ github.event.repository.name }}_$(date +'%Y-%m-%d_%H-%m-%S')" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install pub Dependencies
        run: flutter pub get

      - name: Build iOS App
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r ${{ github.event.repository.name }}.ipa Payload

      - name: Build Android App
        run: flutter build apk --split-per-abi

      - name: Release Apps
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "build/app/outputs/apk/release/*.apk,build/ios/iphoneos/*.ipa"

      # - name: Build release web
      #   run: flutter build web --base-href='/${{ github.event.repository.name }}/'
      # - name: Upload production-ready build files
      #   uses: actions/upload-artifact@v3.1.0
      #   with:
      #     name: production-files
      #     path: ./build/web

  # deploy:
  #   name: Deploy Web
  #   needs: build
  #   runs-on: macos-latest
  #   if: github.ref == 'refs/heads/master'
  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v3.0.0
  #       with:
  #         name: production-files
  #         path: ./build
  #     - name: Deploy to gh-pages
  #       uses: peaceiris/actions-gh-pages@v3.7.3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./build
